version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      -"5000:5000"
    depends_on:
      -db
  db:
    image : postgress:15
    container_name: protgress_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
